### ISSUE TITLE
1.21 server crashing on death

### ISSUE THREAD

**Issue by bridgnanan** [mexicanminion/BountyHunt-Fabric#7]
when a mob that isnt a player kills someone with a bounty (e.g. creeper) on 1.21 bountyhunt fabric, it crashes the server
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2024-06-14 17:14:32
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1548 cannot be cast to class net.minecraft.class_3222 (net.minecraft.class_1548 and net.minecraft.class_3222 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @28feb3fa)
	at net.minecraft.class_3222.checkBounty(class_3222.java:2167)
	at net.minecraft.class_3222.handler$zzl000$bountyhunt$onPlayerDeath(class_3222.java:2143)
	at net.minecraft.class_3222.method_6078(class_3222.java:748)
	at net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at net.minecraft.class_1657.method_5643(class_1657.java:977)
	at net.minecraft.class_3222.method_5643(class_3222.java:811)
	at net.minecraft.class_1927.method_8348(class_1927.java:240)
	at net.minecraft.class_1937.method_46668(class_1937.java:573)
	at net.minecraft.class_3218.method_8454(class_3218.java:1079)
	at net.minecraft.class_1937.method_8437(class_1937.java:543)
	at net.minecraft.class_1548.method_7006(class_1548.java:247)
	at net.minecraft.class_1548.method_5773(class_1548.java:158)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3222.checkBounty(class_3222.java:2167)
	at net.minecraft.class_3222.handler$zzl000$bountyhunt$onPlayerDeath(class_3222.java:2143)
	at net.minecraft.class_3222.method_6078(class_3222.java:748)
	at net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at net.minecraft.class_1657.method_5643(class_1657.java:977)
	at net.minecraft.class_3222.method_5643(class_3222.java:811)
	at net.minecraft.class_1927.method_8348(class_1927.java:240)
	at net.minecraft.class_1937.method_46668(class_1937.java:573)
	at net.minecraft.class_3218.method_8454(class_3218.java:1079)
	at net.minecraft.class_1937.method_8437(class_1937.java:543)
	at net.minecraft.class_1548.method_7006(class_1548.java:247)
	at net.minecraft.class_1548.method_5773(class_1548.java:158)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.class_1548)
	Entity ID: 1374
	Entity Name: Creeper
	Entity's Exact location: 634.61, 62.63, -269.37
	Entity's Block location: World: (634,62,-270), Section: (at 10,14,2 in 39,3,-17; chunk contains blocks 624,-64,-272 to 639,319,-257), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Entity's Momentum: 0.00, -0.02, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by mexicanminion** [comment]
Bug fix for this should be out by tonight (CDT)

**Comment by mexicanminion** [comment]
Issue fixed! Please download 1.3.1 for the fix from modrinth or curseforge
